// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/proto/entry.proto

#include "game/proto/entry.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Entry {
class C2E_LoginRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<C2E_LoginRequest>
      _instance;
} _C2E_LoginRequest_default_instance_;
class E2C_LoginResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<E2C_LoginResponse>
      _instance;
} _E2C_LoginResponse_default_instance_;
}  // namespace Entry
namespace protobuf_game_2fproto_2fentry_2eproto {
static void InitDefaultsC2E_LoginRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Entry::_C2E_LoginRequest_default_instance_;
    new (ptr) ::Entry::C2E_LoginRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Entry::C2E_LoginRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_C2E_LoginRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsC2E_LoginRequest}, {}};

static void InitDefaultsE2C_LoginResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Entry::_E2C_LoginResponse_default_instance_;
    new (ptr) ::Entry::E2C_LoginResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Entry::E2C_LoginResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_E2C_LoginResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsE2C_LoginResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_C2E_LoginRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_E2C_LoginResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Entry::C2E_LoginRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Entry::C2E_LoginRequest, account_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Entry::C2E_LoginRequest, passwd_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Entry::E2C_LoginResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Entry::E2C_LoginResponse, responsetype_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Entry::C2E_LoginRequest)},
  { 7, -1, sizeof(::Entry::E2C_LoginResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Entry::_C2E_LoginRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Entry::_E2C_LoginResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "game/proto/entry.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026game/proto/entry.proto\022\005Entry\"3\n\020C2E_L"
      "oginRequest\022\017\n\007account\030\001 \001(\t\022\016\n\006passwd\030\002"
      " \001(\t\"H\n\021E2C_LoginResponse\0223\n\014responseTyp"
      "e\030\001 \001(\0162\035.Entry.ENTRY_MESSAGE_RESPONSE*/"
      "\n\026ENTRY_RECV_MESSAGETYPE\022\025\n\021C2E_LOGIN_ME"
      "SSAGE\020\000*1\n\026ENTRY_SEND_MESSAGETYPE\022\027\n\023E2C"
      "_LOGIN_R_MESSAGE\020\000*O\n\026ENTRY_MESSAGE_RESP"
      "ONSE\022\006\n\002OK\020\000\022\026\n\022PASSWD_AUTH_FAILED\020\001\022\025\n\021"
      "NO_ACCOUNT_RECORD\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 347);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "game/proto/entry.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_game_2fproto_2fentry_2eproto
namespace Entry {
const ::google::protobuf::EnumDescriptor* ENTRY_RECV_MESSAGETYPE_descriptor() {
  protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_game_2fproto_2fentry_2eproto::file_level_enum_descriptors[0];
}
bool ENTRY_RECV_MESSAGETYPE_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ENTRY_SEND_MESSAGETYPE_descriptor() {
  protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_game_2fproto_2fentry_2eproto::file_level_enum_descriptors[1];
}
bool ENTRY_SEND_MESSAGETYPE_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ENTRY_MESSAGE_RESPONSE_descriptor() {
  protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_game_2fproto_2fentry_2eproto::file_level_enum_descriptors[2];
}
bool ENTRY_MESSAGE_RESPONSE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void C2E_LoginRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int C2E_LoginRequest::kAccountFieldNumber;
const int C2E_LoginRequest::kPasswdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

C2E_LoginRequest::C2E_LoginRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_2fproto_2fentry_2eproto::scc_info_C2E_LoginRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Entry.C2E_LoginRequest)
}
C2E_LoginRequest::C2E_LoginRequest(const C2E_LoginRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.account().size() > 0) {
    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.passwd().size() > 0) {
    passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
  }
  // @@protoc_insertion_point(copy_constructor:Entry.C2E_LoginRequest)
}

void C2E_LoginRequest::SharedCtor() {
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

C2E_LoginRequest::~C2E_LoginRequest() {
  // @@protoc_insertion_point(destructor:Entry.C2E_LoginRequest)
  SharedDtor();
}

void C2E_LoginRequest::SharedDtor() {
  account_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  passwd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void C2E_LoginRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* C2E_LoginRequest::descriptor() {
  ::protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_2fproto_2fentry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const C2E_LoginRequest& C2E_LoginRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_2fproto_2fentry_2eproto::scc_info_C2E_LoginRequest.base);
  return *internal_default_instance();
}


void C2E_LoginRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Entry.C2E_LoginRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool C2E_LoginRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Entry.C2E_LoginRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string account = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account().data(), static_cast<int>(this->account().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Entry.C2E_LoginRequest.account"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string passwd = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_passwd()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->passwd().data(), static_cast<int>(this->passwd().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Entry.C2E_LoginRequest.passwd"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Entry.C2E_LoginRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Entry.C2E_LoginRequest)
  return false;
#undef DO_
}

void C2E_LoginRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Entry.C2E_LoginRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string account = 1;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), static_cast<int>(this->account().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Entry.C2E_LoginRequest.account");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->account(), output);
  }

  // string passwd = 2;
  if (this->passwd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->passwd().data(), static_cast<int>(this->passwd().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Entry.C2E_LoginRequest.passwd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->passwd(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Entry.C2E_LoginRequest)
}

::google::protobuf::uint8* C2E_LoginRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Entry.C2E_LoginRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string account = 1;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), static_cast<int>(this->account().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Entry.C2E_LoginRequest.account");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->account(), target);
  }

  // string passwd = 2;
  if (this->passwd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->passwd().data(), static_cast<int>(this->passwd().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Entry.C2E_LoginRequest.passwd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->passwd(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Entry.C2E_LoginRequest)
  return target;
}

size_t C2E_LoginRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Entry.C2E_LoginRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string account = 1;
  if (this->account().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account());
  }

  // string passwd = 2;
  if (this->passwd().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->passwd());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2E_LoginRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Entry.C2E_LoginRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const C2E_LoginRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const C2E_LoginRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Entry.C2E_LoginRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Entry.C2E_LoginRequest)
    MergeFrom(*source);
  }
}

void C2E_LoginRequest::MergeFrom(const C2E_LoginRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Entry.C2E_LoginRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.account().size() > 0) {

    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  if (from.passwd().size() > 0) {

    passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
  }
}

void C2E_LoginRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Entry.C2E_LoginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2E_LoginRequest::CopyFrom(const C2E_LoginRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Entry.C2E_LoginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2E_LoginRequest::IsInitialized() const {
  return true;
}

void C2E_LoginRequest::Swap(C2E_LoginRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void C2E_LoginRequest::InternalSwap(C2E_LoginRequest* other) {
  using std::swap;
  account_.Swap(&other->account_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  passwd_.Swap(&other->passwd_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata C2E_LoginRequest::GetMetadata() const {
  protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_2fproto_2fentry_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void E2C_LoginResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int E2C_LoginResponse::kResponseTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

E2C_LoginResponse::E2C_LoginResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_2fproto_2fentry_2eproto::scc_info_E2C_LoginResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Entry.E2C_LoginResponse)
}
E2C_LoginResponse::E2C_LoginResponse(const E2C_LoginResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  responsetype_ = from.responsetype_;
  // @@protoc_insertion_point(copy_constructor:Entry.E2C_LoginResponse)
}

void E2C_LoginResponse::SharedCtor() {
  responsetype_ = 0;
}

E2C_LoginResponse::~E2C_LoginResponse() {
  // @@protoc_insertion_point(destructor:Entry.E2C_LoginResponse)
  SharedDtor();
}

void E2C_LoginResponse::SharedDtor() {
}

void E2C_LoginResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* E2C_LoginResponse::descriptor() {
  ::protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_2fproto_2fentry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const E2C_LoginResponse& E2C_LoginResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_2fproto_2fentry_2eproto::scc_info_E2C_LoginResponse.base);
  return *internal_default_instance();
}


void E2C_LoginResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Entry.E2C_LoginResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  responsetype_ = 0;
  _internal_metadata_.Clear();
}

bool E2C_LoginResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Entry.E2C_LoginResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Entry.ENTRY_MESSAGE_RESPONSE responseType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_responsetype(static_cast< ::Entry::ENTRY_MESSAGE_RESPONSE >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Entry.E2C_LoginResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Entry.E2C_LoginResponse)
  return false;
#undef DO_
}

void E2C_LoginResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Entry.E2C_LoginResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Entry.ENTRY_MESSAGE_RESPONSE responseType = 1;
  if (this->responsetype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->responsetype(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Entry.E2C_LoginResponse)
}

::google::protobuf::uint8* E2C_LoginResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Entry.E2C_LoginResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Entry.ENTRY_MESSAGE_RESPONSE responseType = 1;
  if (this->responsetype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->responsetype(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Entry.E2C_LoginResponse)
  return target;
}

size_t E2C_LoginResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Entry.E2C_LoginResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Entry.ENTRY_MESSAGE_RESPONSE responseType = 1;
  if (this->responsetype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->responsetype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void E2C_LoginResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Entry.E2C_LoginResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const E2C_LoginResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const E2C_LoginResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Entry.E2C_LoginResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Entry.E2C_LoginResponse)
    MergeFrom(*source);
  }
}

void E2C_LoginResponse::MergeFrom(const E2C_LoginResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Entry.E2C_LoginResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.responsetype() != 0) {
    set_responsetype(from.responsetype());
  }
}

void E2C_LoginResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Entry.E2C_LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void E2C_LoginResponse::CopyFrom(const E2C_LoginResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Entry.E2C_LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool E2C_LoginResponse::IsInitialized() const {
  return true;
}

void E2C_LoginResponse::Swap(E2C_LoginResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void E2C_LoginResponse::InternalSwap(E2C_LoginResponse* other) {
  using std::swap;
  swap(responsetype_, other->responsetype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata E2C_LoginResponse::GetMetadata() const {
  protobuf_game_2fproto_2fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_2fproto_2fentry_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Entry
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Entry::C2E_LoginRequest* Arena::CreateMaybeMessage< ::Entry::C2E_LoginRequest >(Arena* arena) {
  return Arena::CreateInternal< ::Entry::C2E_LoginRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Entry::E2C_LoginResponse* Arena::CreateMaybeMessage< ::Entry::E2C_LoginResponse >(Arena* arena) {
  return Arena::CreateInternal< ::Entry::E2C_LoginResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
