# proxy settings
export http_proxy="http://127.0.0.1:8118"
export https_proxy="http://127.0.0.1:8118"
git config --global http.proxy http://127.0.0.1:8118
git config --global https.proxy http://127.0.0.1:8118